#define LILPBR_PROPERTIES \
LILPBR_PROPERTY(float,_Cutoff)\
LILPBR_PROPERTY(uint,_DitherRandomize)\
LILPBR_PROPERTY(float4,_Color)\
LILPBR_PROPERTY(float4,_MainTex_ST)\
LILPBR_PROPERTY(uint,_VertexColorMode)\
LILPBR_PROPERTY(float,_BumpScale)\
LILPBR_PROPERTY(float4,_BackfaceColor)\
LILPBR_PROPERTY(float,_Metallic)\
LILPBR_PROPERTY(uint,_MetallicChannel)\
LILPBR_PROPERTY(float,_OcclusionStrength)\
LILPBR_PROPERTY(uint,_OcclusionChannel)\
LILPBR_PROPERTY(float,_Parallax)\
LILPBR_PROPERTY(uint,_HeightChannel)\
LILPBR_PROPERTY(float,_Glossiness)\
LILPBR_PROPERTY(uint,_SmoothnessChannel)\
LILPBR_PROPERTY(float,_ParallaxQuality)\
LILPBR_PROPERTY(float,_ParallaxRandomize)\
LILPBR_PROPERTY(float,_Reflectance)\
LILPBR_PROPERTY(float,_GSAAStrength)\
LILPBR_PROPERTY(float4,_EmissionColor)\
LILPBR_PROPERTY(float4,_EmissionMap_TexelSize)\
LILPBR_PROPERTY(float4,_EmissionSubpixel_ST)\
LILPBR_PROPERTY(float,_Anisotropy)\
LILPBR_PROPERTY(uint,_AnisotropyChannel)\
LILPBR_PROPERTY(float,_ClearCoat)\
LILPBR_PROPERTY(uint,_ClearCoatChannel)\
LILPBR_PROPERTY(float,_ClearCoatSmoothness)\
LILPBR_PROPERTY(uint,_ClearCoatSmoothnessChannel)\
LILPBR_PROPERTY(float,_ClearCoatReflectance)\
LILPBR_PROPERTY(float,_ClearCoatBumpScale)\
LILPBR_PROPERTY(float,_ClearCoatBaseBumpScale)\
LILPBR_PROPERTY(float,_Cloth)\
LILPBR_PROPERTY(float4,_ClothColor)\
LILPBR_PROPERTY(float,_ClothAlbedoBlend)\
LILPBR_PROPERTY(float,_ClothFuzz)\
LILPBR_PROPERTY(float,_ClothDark)\
LILPBR_PROPERTY(float,_Translucent)\
LILPBR_PROPERTY(float4,_TranslucentColor)\
LILPBR_PROPERTY(float,_TranslucentAlbedoBlend)\
LILPBR_PROPERTY(float,_TranslucentRoughness)\
LILPBR_PROPERTY(float,_TranslucentRoughnessBlend)\
LILPBR_PROPERTY(float,_SubsurfaceScattering)\
LILPBR_PROPERTY(uint,_SubsurfaceChannel)\
LILPBR_PROPERTY(float,_SubsurfaceThickness)\
LILPBR_PROPERTY(float,_SubsurfaceRim)\
LILPBR_PROPERTY(float4,_SubsurfaceColor)\
LILPBR_PROPERTY(float,_SubsurfaceAlbedoBlend)\
LILPBR_PROPERTY(float,_ScreeningScaleX)\
LILPBR_PROPERTY(float,_ScreeningScaleY)\
LILPBR_PROPERTY(float,_ScreeningNoiseStrength)\
LILPBR_PROPERTY(uint,_DetailUVMode1)\
LILPBR_PROPERTY(uint,_DetailAlbedoBlend1)\
LILPBR_PROPERTY(float4,_DetailTex1_ST)\
LILPBR_PROPERTY(float,_DetailBumpScale1)\
LILPBR_PROPERTY(uint,_DetailBumpMapBlend1)\
LILPBR_PROPERTY(float4,_DetailProjection1)\
LILPBR_PROPERTY(float,_DetailProjectionSharpness1)\
LILPBR_PROPERTY(float,_DetailProjectionThreshold1)\
LILPBR_PROPERTY(uint,_DetailUVMode2)\
LILPBR_PROPERTY(uint,_DetailAlbedoBlend2)\
LILPBR_PROPERTY(float4,_DetailTex2_ST)\
LILPBR_PROPERTY(float,_DetailBumpScale2)\
LILPBR_PROPERTY(uint,_DetailBumpMapBlend2)\
LILPBR_PROPERTY(float4,_DetailProjection2)\
LILPBR_PROPERTY(float,_DetailProjectionSharpness2)\
LILPBR_PROPERTY(float,_DetailProjectionThreshold2)\
LILPBR_PROPERTY(uint,_DetailUVMode3)\
LILPBR_PROPERTY(uint,_DetailAlbedoBlend3)\
LILPBR_PROPERTY(float3,_DetailTex3_ST)\
LILPBR_PROPERTY(float,_DetailBumpScale3)\
LILPBR_PROPERTY(uint,_DetailBumpMapBlend3)\
LILPBR_PROPERTY(float4,_DetailProjection3)\
LILPBR_PROPERTY(float,_DetailProjectionSharpness3)\
LILPBR_PROPERTY(float,_DetailProjectionThreshold3)\
LILPBR_PROPERTY(uint,_DetailUVMode4)\
LILPBR_PROPERTY(uint,_DetailAlbedoBlend4)\
LILPBR_PROPERTY(float4,_DetailTex4_ST)\
LILPBR_PROPERTY(float,_DetailBumpScale4)\
LILPBR_PROPERTY(uint,_DetailBumpMapBlend4)\
LILPBR_PROPERTY(float4,_DetailProjection4)\
LILPBR_PROPERTY(float,_DetailProjectionSharpness4)\
LILPBR_PROPERTY(float,_DetailProjectionThreshold4)\
LILPBR_PROPERTY(uint,_WetnessChannel)\
LILPBR_PROPERTY(float,_WetnessBumpScale)\
LILPBR_PROPERTY(float4,_WetnessBumpMap_ST)\
LILPBR_PROPERTY(float,_WetnessBumpScroll)\
LILPBR_PROPERTY(float,_WetnessDepth)\
LILPBR_PROPERTY(float4,_WetnessColor)\
LILPBR_PROPERTY(float,_RainScale)\
LILPBR_PROPERTY(float,_RainSpeed)\
LILPBR_PROPERTY(float,_RainLoop)\
LILPBR_PROPERTY(float4,_WindDirection)\
LILPBR_PROPERTY(uint,_WindClothMode)\
LILPBR_PROPERTY(uint,_WindTreeMode)\
LILPBR_PROPERTY(float,_WindBranchSoftness)\
LILPBR_PROPERTY(float,_WindLeafSoftness)\
LILPBR_PROPERTY(float,_DistanceFade)\
LILPBR_PROPERTY(float,_DistanceFadeStart)\
LILPBR_PROPERTY(float,_DistanceFadeEnd)\
LILPBR_PROPERTY(uint,_ShaderLayer)

#define LILPBR_TEXTURES \
LILPBR_TEXTURE(Texture2D,_MainTex)\
LILPBR_TEXTURE(Texture2D,_AtrasMask)\
LILPBR_TEXTURE(Texture2D,_BumpMap)\
LILPBR_TEXTURE(Texture2D,_BackfaceTex)\
LILPBR_TEXTURE(Texture2D,_PBRMap)\
LILPBR_TEXTURE(Texture2D,_MetallicGlossMap)\
LILPBR_TEXTURE(Texture2D,_OcclusionMap)\
LILPBR_TEXTURE(Texture2D,_ParallaxMap)\
LILPBR_TEXTURE(Texture2D,_SmoothnessMap)\
LILPBR_TEXTURE(Texture2D,_EmissionMap)\
LILPBR_TEXTURE(Texture2D,_EmissionSubpixel)\
LILPBR_TEXTURE(Texture2D,_AnisotropyDirection)\
LILPBR_TEXTURE(Texture2D,_AnisotropyMask)\
LILPBR_TEXTURE(Texture2D,_ClearCoatMask)\
LILPBR_TEXTURE(Texture2D,_ClearCoatBumpMap)\
LILPBR_TEXTURE(Texture2D,_SubsurfaceMap)\
LILPBR_TEXTURE(Texture2D,_DetailMask)\
LILPBR_TEXTURE(Texture2D,_DetailTex1)\
LILPBR_TEXTURE(Texture2D,_DetailBumpMap1)\
LILPBR_TEXTURE(Texture2D,_DetailTex2)\
LILPBR_TEXTURE(Texture2D,_DetailBumpMap2)\
LILPBR_TEXTURE(Texture2D,_DetailTex3)\
LILPBR_TEXTURE(Texture2D,_DetailBumpMap3)\
LILPBR_TEXTURE(Texture2D,_DetailTex4)\
LILPBR_TEXTURE(Texture2D,_DetailBumpMap4)\
LILPBR_TEXTURE(Texture2D,_WetnessMask)\
LILPBR_TEXTURE(Texture2D,_WetnessBumpMap)\
LILPBR_TEXTURE(Texture2D,_DitherTex)\

#define LILPBR_SAMPLERS \
LILPBR_SAMPLER(SamplerState,sampler_MainTex)\
LILPBR_SAMPLER(SamplerState,sampler_PBRMap)\
LILPBR_SAMPLER(SamplerState,sampler_ParallaxMap)
